### ISSUE TITLE
Consider renaming to wren-ice40-hat or wren-fpga-hat

### ISSUE THREAD

**Issue by mithro** [Wren6991/FPGA-HAT#2]
This is a cool little board but it has a name collision with a lot of other FPGA RPi hats. Any chance you would consider renaming it to be slightly less generic? `wren-fpga-hat` or `wren-ice40-hat` would both be great!

**Comment by Wren6991** [comment]
At your special request this is now called `Snowflake FPGA HAT`

**Comment by mithro** [comment]
Great name! Thank you!
